name: Check

on:
  push:
    branches: [ "develop", "main" ]
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    strategy:
      matrix:
        node-version: [20.x]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint:fix

